name: 'repoman'
on: [push, pull_request]
jobs:
    repoman:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: lucianposton/repoman-ebuild-qa-action@v1
